version: "3"

services:
  ls_redis:
    container_name: ls_redis
    image: "redis:latest"
    expose:
      - 6379
    ports:
      - "6379:6379"

  ls_mongo:
    container_name: ls_mongo
    image: "mongo:latest"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    expose:
      - 27017
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
# networks:
#   default:
#     driver: bridge

volumes:
  my-db:
  mongodb_data_container:
